-- Migration 015: Tags System
-- Plant tags for compliance tracking. Auto-generated by default,
-- or pre-issued via CSV upload for Metrc-integrated facilities.

-- ============================================================================
-- 1. Tags pool table — stores all tags (auto-generated + uploaded)
-- ============================================================================
CREATE TABLE IF NOT EXISTS tags (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    tag_number      VARCHAR(255) NOT NULL,
    tag_type        VARCHAR(20) NOT NULL DEFAULT 'plant'
                        CHECK (tag_type IN ('plant', 'batch')),
    status          VARCHAR(20) NOT NULL DEFAULT 'available'
                        CHECK (status IN ('available', 'assigned', 'voided')),

    -- Assignment tracking
    assigned_to_plant_id    UUID REFERENCES plants(id) ON DELETE SET NULL,
    assigned_to_batch_id    UUID REFERENCES plant_batches(id) ON DELETE SET NULL,
    assigned_at             TIMESTAMP WITH TIME ZONE,

    -- Timestamps
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Unique tag number per company
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_company_number
    ON tags(company_id, tag_number);

-- Fast pool lookups (available tags by type)
CREATE INDEX IF NOT EXISTS idx_tags_pool
    ON tags(company_id, status, tag_type);

-- Lookup by assigned plant/batch
CREATE INDEX IF NOT EXISTS idx_tags_plant
    ON tags(assigned_to_plant_id) WHERE assigned_to_plant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tags_batch
    ON tags(assigned_to_batch_id) WHERE assigned_to_batch_id IS NOT NULL;

-- Auto-update timestamp
CREATE TRIGGER update_tags_updated_at
    BEFORE UPDATE ON tags
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- 2. Tag columns on plants and plant_batches (denormalized for read convenience)
-- ============================================================================
ALTER TABLE plants ADD COLUMN IF NOT EXISTS tag VARCHAR(255);
ALTER TABLE plant_batches ADD COLUMN IF NOT EXISTS tag VARCHAR(255);

-- ============================================================================
-- 3. Tag settings — per-company configuration
-- ============================================================================
CREATE TABLE IF NOT EXISTS tag_settings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id      UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

    use_tags            BOOLEAN NOT NULL DEFAULT false,
    tag_source          VARCHAR(20) NOT NULL DEFAULT 'auto'
                            CHECK (tag_source IN ('auto', 'upload')),
    tag_on_phase        VARCHAR(20) NOT NULL DEFAULT 'nursery_to_veg'
                            CHECK (tag_on_phase IN ('nursery_to_veg', 'veg_to_flower')),
    require_batch_tag   BOOLEAN NOT NULL DEFAULT false,
    auto_tag_prefix     VARCHAR(20) NOT NULL DEFAULT 'PLT',
    auto_tag_counter    INTEGER NOT NULL DEFAULT 0,

    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    UNIQUE(company_id)
);

CREATE TRIGGER update_tag_settings_updated_at
    BEFORE UPDATE ON tag_settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
